// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;

public type TaskUpdate record {
    string title?;
    "low"|"medium"|"high" priority?;
    string? dueDate?;
    string[] tags?;
};

public type Task record {
    string id;
    string title;
    "open"|"completed" status;
    "low"|"medium"|"high" priority;
    string? dueDate?;
    string[] tags?;
    string createdAt;
    string updatedAt;
};

public type ErrorNotFound record {|
    *http:NotFound;
    Error body;
|};

public type ErrorInternalServerError record {|
    *http:InternalServerError;
    Error body;
|};

public type TaskOk record {|
    *http:Ok;
    Task body;
|};

public type TaskCreated record {|
    *http:Created;
    Task body;
|};

public type TaskInput record {
    string title;
    "low"|"medium"|"high" priority;
    string? dueDate?;
    string[] tags?;
};

public type TagListResponse record {
    # total matching items
    int count;
    # relative URI of the next page
    string? next?;
    # relative URI of the previous page
    string? previous?;
    Tag[] data;
};

public type TaskListResponse record {
    # total matching items
    int count;
    # relative URI of the next page
    string? next?;
    # relative URI of the previous page
    string? previous?;
    Task[] data;
};

public type Error record {
    # HTTP or application error code
    int code;
    # short human-readable label
    string message;
    # detailed explanation
    string description?;
    # URI to documentation
    string moreInfo?;
};

public type ErrorBadRequest record {|
    *http:BadRequest;
    Error body;
|};

public type Tag record {
    string name;
};

public type ErrorUnauthorized record {|
    *http:Unauthorized;
    Error body;
|};
